[phases]
install = "npm install"
build = "npx tsc"  # Compiles TypeScript files in your project
start = "node dist/index.js"  # Starts the compiled JavaScript file

[language]
type = "nodejs"
version = "14"  # Set Node.js version compatible with your project
