version: '1.0'
services:
  my-serverless-function:
    runtime: nodejs14  # Specify runtime compatible with your setup
    build: npm install && npx tsc  # Installs dependencies and compiles TypeScript
    start: node dist/index.js      # Starts the compiled JS file
    routes:
      - path: /api/custom-path  # The custom path you want
